name: .NET build pipeline

# Triggers
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

#: Jobs to execute
jobs:
  ## Build all projects
  build:
    runs-on: ubuntu-latest #self-hosted

    steps:
    ### Checkout repo
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    ### Generate version number
    - name: Get version
      id: get_version
      uses: kingtechnl/githubactions/gitversion@main
    ### Create and publish docker image to DockerHub
    - name: Build and publish docker image
      if: success()
      uses: kingtechnl/githubactions/publish-docker@main
      with:
        registry_username: "${{ secrets.DOCKERHUB_USERNAME }}"
        registry_password: "${{ secrets.DOCKERHUB_TOKEN }}"
        image_name: "kingtech_filecopy"
        tags: "latest"
        docker_file: "DockerFileCopy/Dockerfile"